apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: https://kubernetes.docker.internal:6443
    name: docker-desktop
  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: https://34.79.99.90
    name: gke_springboot-automation_europe-west1_autopilot-cluster-1
  - cluster:
      certificate-authority: /home/yigitwsl/.minikube/ca.crt
      extensions:
        - extension:
            last-update: Thu, 22 Aug 2024 01:09:32 +03
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: cluster_info
      server: https://127.0.0.1:65415
    name: minikube
contexts:
  - context:
      cluster: docker-desktop
      user: docker-desktop
    name: docker-desktop
  - context:
      cluster: gke_springboot-automation_europe-west1_autopilot-cluster-1
      user: gke_springboot-automation_europe-west1_autopilot-cluster-1
    name: gke_springboot-automation_europe-west1_autopilot-cluster-1
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Thu, 22 Aug 2024 01:09:32 +03
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: docker-desktop
    user:
      client-certificate-data: REDACTED
      client-key-data: REDACTED
  - name: gke_springboot-automation_europe-west1_autopilot-cluster-1
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args: null
        command: gke-gcloud-auth-plugin
        env: null
        installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
          https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
        interactiveMode: IfAvailable
        provideClusterInfo: true
  - name: minikube
    user:
      client-certificate: /home/yigitwsl/.minikube/profiles/minikube/client.crt
      client-key: /home/yigitwsl/.minikube/profiles/minikube/client.key