apiVersion: v1
clusters:
  - cluster:
      certificate-authority: /home/yigitwsl/.minikube/ca.crt
      extensions:
        - extension:
            last-update: Thu, 22 Aug 2024 01:09:32 +03
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: cluster_info
      server: https://127.0.0.1:51683
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Thu, 22 Aug 2024 01:09:32 +03
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: /home/yigitwsl/.minikube/profiles/minikube/client.crt
      client-key: /home/yigitwsl/.minikube/profiles/minikube/client.key