apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: test
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30443
  type: NodePort
  